<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SURIMI.Datamodel</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>SURIMI.Datamodel</PackageId>
    <Authors>EII</Authors>
    <Description>SURIMI DTO Datamodel</Description>
    <Title>The SURIMI Datamodel</Title>
    <PackageProjectUrl>https://github.com/Official-EwE/SURIMI-Datamodel-DotNet</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Official-EwE/SURIMI-Datamodel-DotNet</RepositoryUrl>
    <PackageReleaseNotes>Initial version</PackageReleaseNotes>
    <PackageLicenseExpression>EUPL-1.2-or-later</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <IncludeSymbols>True</IncludeSymbols>
    <IncludeReferencedProjects>True</IncludeReferencedProjects>
    <Company>EII</Company>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="True" PackagePath="\" />
  </ItemGroup>
</Project>
